import type { Metadata } from 'next';
import { Nunito, Roboto_Mono } from 'next/font/google';
import './globals.css';
import Footer from './components/Footer';

// Fonts.
const nunito = Nunito({
  subsets: ['latin'],
  variable: '--font-nunito',
});

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
});

// Metadata.
export const metadata: Metadata = {
  title: 'Test next app',
  description: 'Generated by create next app',
};

export interface LayoutProps {
  children: React.ReactNode;
}

const RootLayout = ({ children }: LayoutProps): React.JSX.Element => {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${robotoMono.variable} flex h-screen min-h-screen w-full flex-col`}
      >
        <main className="flex h-full w-full grow flex-col">{children}</main>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
